apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGR0bGxjejU2
  CLOUDINARY_KEY: OTE0NTQ5NjE4ODY2NjQ2
  CLOUDINARY_SECRET: VXhCbndEdHZtMGdBSEUtS2F5V3oxam5ZemNn
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhM1Z0WVhJME9TSXNJbUVpT2lKamJXMXJNbTgyTmpJeGJIaGtNbTl2Wm5aMVpIQmlhV1UxSW4wLnhUMnVLR3N6NmNwZjFyRDBRNDkyVlE=
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjpQYXZhbjIzMjdAY2x1c3RlcjAuYjhoajg0YS5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
